#!/bin/sh

if [ "$1" = "clean" ]; then
	echo ":: Cleaning ..."
	rm -rf ctrpluginframework
	git clone https://gitlab.com/thepixellizeross/ctrpluginframework.git -b develop
fi
if [ -e ctrpluginframework ]; then
	echo ":: Patching..."
	cp -r __patch__/* ctrpluginframework/
	echo ":: Building..."
	cd ctrpluginframework
	sudo make
	sudo chown 1000:1000 -R ./* # Don't want to make a mess,
								# so you can delete these as a regular user
	cd ..
else
	echo "FAIL: Do '$0 clean'"
fi
